"""
Generates today's HBM lesson without an external API by embedding the lesson
content directly. Mirrors generate_lesson.py's output exactly.
"""
import json
import os
import re
import urllib.request
from datetime import date, datetime
from pathlib import Path
from zoneinfo import ZoneInfo
import subprocess as _sp
import importlib.util

today = date.today().isoformat()
now_et = datetime.now(ZoneInfo("America/New_York"))
date_str = now_et.strftime("%A, %b %d %Y")
lesson_dir = "daily-lessons"
os.makedirs(lesson_dir, exist_ok=True)

# ── Curriculum ─────────────────────────────────────────────────────────────────
curriculum_path = Path("curriculum.json")
with open(curriculum_path, encoding="utf-8") as f:
    curriculum = json.load(f)

def next_topic():
    for module in curriculum["modules"]:
        for topic in module["topics"]:
            if not topic["done"]:
                return module, topic
    return None, None

def mark_done(topic_id):
    for module in curriculum["modules"]:
        for topic in module["topics"]:
            if topic["id"] == topic_id:
                topic["done"] = True
    with open(curriculum_path, "w", encoding="utf-8") as f:
        json.dump(curriculum, f, ensure_ascii=False, indent=2)

def curriculum_progress():
    total = sum(len(m["topics"]) for m in curriculum["modules"])
    done = sum(1 for m in curriculum["modules"] for t in m["topics"] if t["done"])
    return done, total

module, topic_item = next_topic()
if topic_item is None:
    print("Curriculum complete!")
    exit(0)

topic_title = topic_item["title"]
module_name = module["name"]
topic_id = topic_item["id"]
done_count, total_count = curriculum_progress()

print(f"Module {topic_id}: {topic_title}")

# ── Lesson content (generated by Claude) ─────────────────────────────────────
lesson = {
  "topic": "HBM in HPC Systems: Bandwidth Optimization and Testing",
  "summary": "HBM's 900+ GB/s aggregate bandwidth enables HPC workloads; maximizing efficiency requires coalesced access patterns, topology-aware mapping, and thermal-stress ATE validation.",
  "sections": [
    {
      "title": "HBM Bandwidth Architecture in HPC",
      "content": (
        "<p>High-bandwidth memory achieves its extraordinary throughput through a combination of "
        "a wide parallel interface, 3D stacking, and short interconnect distances via silicon "
        "interposer or embedded bridge. A single HBM2e stack exposes a <strong>1024-bit</strong> "
        "wide interface organized as 8 channels x 128 bits, with each channel subdivided into two "
        "64-bit pseudo-channels in HBM2e/HBM3. Operating at up to 3.6 GT/s per pin, a single "
        "HBM2e stack delivers ~460 GB/s; HBM3 reaches ~665 GB/s per stack at 6.4 GT/s.</p>"
        "<p>In HPC system designs, multiple stacks are placed in a 2.5D or 3D configuration "
        "around a compute die. AMD MI300X integrates 8 HBM3 stacks for an aggregate "
        "<strong>5.3 TB/s</strong> of memory bandwidth, while NVIDIA H100 SXM5 achieves "
        "<strong>3.35 TB/s</strong> with 6 HBM3 stacks. The critical metric for test engineers is "
        "not peak bandwidth but <em>sustained bandwidth efficiency</em> -- the ratio of effective "
        "throughput to peak rated bandwidth under realistic workload patterns.</p>"
        "<p>The PHY layer implements DLL-based timing calibration on a per-channel basis. "
        "JEDEC JESD235C specifies <code>tRCD</code>, <code>tCL</code>, and <code>tRP</code> "
        "timing parameters that bound worst-case bandwidth: a column access latency of CL=14 at "
        "3.2 GT/s means 8.75 ns of latency overhead per DRAM transaction, emphasizing the "
        "importance of burst mode and access coalescing for HPC efficiency.</p>"
      )
    },
    {
      "title": "Bandwidth-Bound Workloads and the Roofline Model",
      "content": (
        "<p>The <strong>roofline model</strong> (Williams et al., 2009) provides a quantitative "
        "framework for determining whether an HPC kernel is compute-bound or memory-bandwidth-bound. "
        "It plots achievable FLOP/s against arithmetic intensity (FLOPs per byte of DRAM traffic). "
        "The model defines two performance ceilings:</p>"
        "<ul>"
        "<li><strong>Compute ceiling</strong>: peak FLOP/s of the processor (e.g., 989 TFLOPS FP8 for H100)</li>"
        "<li><strong>Bandwidth ceiling</strong>: peak_BW x arithmetic_intensity (GB/s x FLOP/byte)</li>"
        "</ul>"
        "<p>Kernels with arithmetic intensity below the <em>ridge point</em> "
        "(compute_ceiling / bandwidth_ceiling) are bandwidth-bound. For H100 SXM5, the ridge point "
        "is 989 TFLOPS / 3.35 TB/s ~= 295 FLOP/byte. Matrix-vector multiplication at ~2 FLOP/byte "
        "is deeply bandwidth-bound; dense GEMM at ~512 FLOP/byte is compute-bound.</p>"
        "<p>For HBM test engineers, this model dictates the test stimulus design: HPC systems "
        "running bandwidth-bound AI inference, graph analytics, or genomics workloads will saturate "
        "HBM bandwidth continuously, creating sustained high-current conditions that GDDR-based "
        "systems rarely encounter. ATE patterns must replicate these access profiles to expose "
        "thermal and margin failures that only appear under sustained bandwidth load.</p>"
      )
    },
    {
      "title": "Memory Access Pattern Optimization for Peak Bandwidth",
      "content": (
        "<p>Achieving close to peak HBM bandwidth in HPC applications requires disciplined "
        "management of access patterns at multiple levels:</p>"
        "<ul>"
        "<li><strong>Access coalescing</strong>: HBM channels have a minimum burst length of BL4 "
        "(32 bytes per pseudo-channel, 64 bytes per full channel). Scattered 4-byte reads activate "
        "a full 64-byte cache line while consuming only 4 bytes -- 16x bandwidth waste. Coalescing "
        "adjacent thread accesses into aligned 128-byte transactions maximizes bus utilization.</li>"
        "<li><strong>Bank group interleaving</strong>: HBM3 implements 4 bank groups x 4 banks "
        "per pseudo-channel. Sequential addresses should map across bank groups to exploit "
        "<code>tCCDS_BG</code> (2 cycles) vs. <code>tCCDS</code> (4 cycles) timing advantage, "
        "raising effective bandwidth by up to 30%.</li>"
        "<li><strong>Row buffer locality</strong>: Keep consecutive accesses within the same DRAM "
        "row (8 KB per HBM row) to exploit open-page policy; avoid mixed sequential/random "
        "patterns that force excessive ACT/PRE cycles.</li>"
        "<li><strong>Pseudo-channel symmetry</strong>: Balance traffic evenly between the two "
        "pseudo-channels of each channel to avoid arbitration stall -- asymmetric loading reduces "
        "effective bandwidth by 10-25% in measured HPC traces.</li>"
        "</ul>"
        "<p>Software tools such as AMD <code>rocm-bandwidth-test</code> and NVIDIA "
        "<code>bandwidthTest</code> provide first-order validation; production profiling requires "
        "hardware performance counters exposed via <code>perf</code>, NVIDIA Nsight, or ROCProfiler "
        "to measure <em>HBM read/write bandwidth utilization</em> at the controller level.</p>"
      )
    },
    {
      "title": "Multi-Stack Topology and NUMA Effects",
      "content": (
        "<p>Systems with multiple HBM stacks present a Non-Uniform Memory Access (NUMA) topology "
        "even within a single chip. Each compute cluster or CU group has lower-latency, "
        "higher-bandwidth access to its local HBM stack than to remote stacks accessed via the "
        "on-die interconnect fabric. This intra-chip NUMA effect is significant: on AMD MI300X, "
        "local HBM access latency is ~100 ns while remote HBM (across the die-to-die interface) "
        "incurs ~180-220 ns, reducing effective bandwidth for cross-stack traffic.</p>"
        "<p>HPC software must implement topology-aware data placement -- the GPU driver and runtime "
        "(HIP, CUDA) expose APIs for explicit memory placement on specific HBM partitions. For test "
        "engineers validating multi-stack HBM systems:</p>"
        "<ul>"
        "<li>Test patterns must exercise <strong>all cross-stack traffic combinations</strong> to "
        "detect interconnect defects not visible in single-stack tests</li>"
        "<li>Concurrent multi-stack access patterns stress the shared NoC (Network-on-Chip), "
        "potentially exposing arbitration bugs at peak bandwidth that do not appear in sequential "
        "per-stack validation</li>"
        "<li>Power delivery must be validated under simultaneous multi-stack read bursts -- "
        "peak current draw can reach 150+ A for an 8-stack configuration at full BW utilization</li>"
        "</ul>"
      )
    },
    {
      "title": "Testing Methodology for HBM in HPC Systems",
      "content": (
        "<p>Validating HBM for HPC deployment extends well beyond JEDEC compliance testing. "
        "The test strategy must cover three regimes:</p>"
        "<p><strong>1. Characterization (wafer / KGD)</strong>: Full JEDEC parametric testing "
        "per JESD235C -- AC/DC specs, timing margins (<code>tRCD</code>, <code>tRAS</code>, "
        "<code>tRP</code>), address/data eye diagrams, and DQ receiver sensitivity. Critical "
        "HPC-specific additions: measure <em>sustained bandwidth efficiency</em> over 60-second "
        "thermal soak at Tj = 85 C to catch self-heating-induced margin loss.</p>"
        "<p><strong>2. System-level functional test (post-assembly)</strong>: After 2.5D/3DIC "
        "integration, run stress patterns that replicate production HPC workloads: "
        "sequential streaming (STREAM benchmark equivalent), random-access patterns (GUPS), "
        "and mixed read/write at 70%/30% ratio typical of ML inference. Pattern duration "
        "should exceed thermal equilibration time (~30 s for a fully integrated package).</p>"
        "<p><strong>3. Burn-in and reliability screening</strong>: HBM in HPC runs hotter and "
        "at higher average utilization than consumer workloads. Elevated-voltage burn-in at "
        "VDD = 1.2V (nominal 1.1V for HBM3), junction temperature 95 C, combined with "
        "worst-case access patterns for 48-96 hours screens latent defects. The ATE must "
        "provide per-stack current monitoring at millisecond resolution to flag transient "
        "overcurrent events indicative of weak cell arrays.</p>"
        "<p>Key ATE measurements: <code>IDD4R</code> (active read current), "
        "<code>IDD4W</code> (active write current), and "
        "<code>IDD6</code> (self-refresh) vs. temperature. "
        "Compare against JEDEC maximum ratings and flag units exceeding 5% of spec as marginal.</p>"
      )
    }
  ],
  "key_takeaways": [
    "HBM's 1024-bit wide interface enables 460-665 GB/s per stack; HPC systems aggregate multiple stacks to reach multi-TB/s bandwidth that GDDR cannot match.",
    "The roofline model identifies bandwidth-bound HPC kernels (arithmetic intensity < ridge point); ATE patterns should mirror these sustained high-utilization access profiles.",
    "Access coalescing, bank group interleaving, and pseudo-channel balance are the primary software levers to close the gap between peak and effective HBM bandwidth.",
    "Multi-stack HPC configurations introduce intra-chip NUMA effects; test coverage must include all cross-stack traffic combinations and concurrent multi-stack stress patterns.",
    "HPC burn-in must run at elevated VDD and junction temperature with production-representative access patterns for 48-96 hours to screen latent defects not visible in standard JEDEC testing."
  ],
  "references": [
    {
      "title": "High Bandwidth Memory (HBM) DRAM Standard",
      "type": "JEDEC",
      "detail": "JESD235C -- Sections 6 (AC specs/timing), 7 (pseudo-channel mode), 8 (electrical characteristics)"
    },
    {
      "title": "Roofline: An Insightful Visual Performance Model for Multicore Architectures",
      "type": "IEEE",
      "detail": "Williams, Waterman, Patterson -- Communications of the ACM, Vol. 52 No. 4, 2009"
    },
    {
      "title": "NVIDIA H100 SXM5 GPU Architecture Whitepaper",
      "type": "Datasheet",
      "detail": "NVIDIA 2022 -- HBM3 6-stack configuration, 3.35 TB/s aggregate bandwidth specification"
    },
    {
      "title": "AMD Instinct MI300X Accelerator Architecture",
      "type": "Datasheet",
      "detail": "AMD 2023 Technical Reference -- 8x HBM3 stacks, 5.3 TB/s, multi-die NUMA topology"
    },
    {
      "title": "HBM PHY Architecture and High-Speed Testing Challenges",
      "type": "Paper",
      "detail": "Synopsys -- DesignCon 2023; covers PHY DLL calibration, eye margin measurement methodology"
    },
    {
      "title": "Memory Systems: Cache, DRAM, Disk",
      "type": "Book",
      "detail": "Jacob, Ng, Wang -- Morgan Kaufmann 2007; DRAM timing parameter analysis, Chapters 6-8"
    }
  ],
  "additional_learning": {
    "title": "Pseudo-Channel Mode and Bandwidth Testing Implications",
    "content": (
      "HBM2e and HBM3 introduce pseudo-channel (PC) mode, splitting each 128-bit channel into "
      "two independent 64-bit pseudo-channels that share a common command/address bus but have "
      "separate data buses and independent bank state machines. This halves the minimum transaction "
      "granularity from 256 bytes (full channel, BL4) to 128 bytes per PC, improving bandwidth "
      "efficiency for the sparse, irregular access patterns common in graph analytics and genomics "
      "workloads. For ATE validation, pseudo-channel mode requires that test patterns independently "
      "stress each PC -- including concurrent conflicting accesses to the shared CA bus -- to "
      "expose arbitration logic bugs where one PC starves the other under asymmetric load, a "
      "failure mode that is invisible in single-channel sequential test patterns."
    )
  }
}

topic = lesson["topic"]
summary = lesson["summary"]
sections = lesson["sections"]
takeaways = lesson["key_takeaways"]
references = lesson.get("references", [])
additional = lesson.get("additional_learning")

slug = re.sub(r'[^a-z0-9]+', '-', topic.lower()).strip('-')[:60]
base_name = f"{today}-{slug}"

# ── Markdown ──────────────────────────────────────────────────────────────────
md_lines = [f"# {topic}\n", f"*{date_str}*\n", f"*Module {topic_id} -- {module_name}*\n"]
for s in sections:
    md_lines.append(f"## {s['title']}\n")
    content = (s["content"]
               .replace("<p>", "").replace("</p>", "\n")
               .replace("<strong>", "**").replace("</strong>", "**")
               .replace("<code>", "`").replace("</code>", "`")
               .replace("<ul>", "").replace("</ul>", "")
               .replace("<li>", "- ").replace("</li>", ""))
    md_lines.append(content + "\n")
md_lines.append("## Key Takeaways\n")
for t in takeaways:
    md_lines.append(f"- {t}")
if references:
    md_lines.append("\n## References\n")
    for i, r in enumerate(references, 1):
        md_lines.append(f"{i}. **[{r['type']}]** {r['title']} -- {r['detail']}")
if additional:
    md_lines.append(f"\n## Additional Learning: {additional['title']}\n")
    md_lines.append(additional["content"])

md_path = os.path.join(lesson_dir, f"{base_name}.md")
with open(md_path, "w", encoding="utf-8") as f:
    f.write("\n".join(md_lines) + "\n")

# ── HTML ──────────────────────────────────────────────────────────────────────
sections_html = "".join(
    f'<div class="section"><h2>{s["title"]}</h2>{s["content"]}</div>\n'
    for s in sections
)
takeaways_html = "".join(f"<li>{t}</li>" for t in takeaways)

additional_html = ""
if additional:
    additional_html = (
        f'<div class="additional">'
        f'<h2>&#x1F50D; Additional Learning</h2>'
        f'<a href="../additional-learning.html#module-{topic_id.split(".")[0]}">'
        f'{additional["title"]}</a>'
        f'</div>'
    )

if references:
    ref_items = "".join(
        f'<div class="ref-item"><span class="ref-type">{r["type"]}</span>'
        f'<div><div class="ref-title">{r["title"]}</div>'
        f'<div class="ref-detail">{r["detail"]}</div></div></div>'
        for r in references
    )
    references_html = f'<div class="references"><h2>📚 References</h2>{ref_items}</div>'
else:
    references_html = ""

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{topic}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         background: #0f1117; color: #e2e8f0; padding: 20px; max-width: 760px; margin: 0 auto; }}
  header {{ margin-bottom: 28px; }}
  h1 {{ font-size: 1.6rem; font-weight: 700; color: #f8fafc; line-height: 1.4; margin-bottom: 6px; }}
  .meta {{ font-size: 0.9rem; color: #64748b; margin-top: 6px; }}
  .badge {{ display: inline-block; background: #1e3a5f; color: #60a5fa;
            font-size: 0.78rem; font-weight: 600; padding: 2px 8px; border-radius: 4px;
            letter-spacing: .05em; text-transform: uppercase; margin-right: 8px; }}
  .module-badge {{ background: #1a2e1a; color: #86efac; }}
  .section {{ background: #1e2330; border-radius: 12px; padding: 20px 22px; margin-bottom: 14px; }}
  h2 {{ font-size: 1.15rem; font-weight: 700; color: #93c5fd; margin-bottom: 14px; }}
  p {{ font-size: 1.05rem; line-height: 1.8; color: #cbd5e1; margin-bottom: 12px; }}
  ul {{ padding-left: 20px; margin-bottom: 12px; }}
  li {{ font-size: 1.05rem; line-height: 1.8; color: #cbd5e1; margin-bottom: 6px; }}
  code {{ background: #0f172a; color: #a5f3fc; padding: 2px 6px; border-radius: 4px;
          font-size: 0.95em; font-family: 'SF Mono', Consolas, monospace; }}
  strong {{ color: #f1f5f9; }}
  .takeaways {{ background: #162032; border-left: 3px solid #3b82f6;
                border-radius: 0 10px 10px 0; padding: 18px 22px; margin-bottom: 14px; }}
  .takeaways h2 {{ color: #60a5fa; margin-bottom: 12px; }}
  .takeaways li {{ color: #94a3b8; }}
  .references {{ background: #1e2330; border-radius: 12px; padding: 18px 22px; margin-bottom: 14px; }}
  .references h2 {{ font-size: 1.15rem; font-weight: 700; color: #93c5fd; margin-bottom: 12px; }}
  .ref-item {{ display: flex; gap: 10px; align-items: baseline; padding: 8px 0;
               border-bottom: 1px solid #0f172a; font-size: 1rem; }}
  .ref-item:last-child {{ border-bottom: none; }}
  .ref-type {{ flex-shrink: 0; background: #0f172a; color: #7dd3fc; font-size: 0.75rem;
               font-weight: 700; padding: 2px 7px; border-radius: 4px; letter-spacing: .04em; }}
  .ref-title {{ color: #e2e8f0; font-weight: 600; }}
  .ref-detail {{ color: #64748b; font-size: 0.9rem; }}
  .additional {{ background: #1a1f2e; border-left: 3px solid #a78bfa; border-radius: 0 8px 8px 0;
                  padding: 14px 18px; margin-bottom: 14px; }}
  .additional h2 {{ color: #a78bfa; font-size: 0.72rem; font-weight: 700; text-transform: uppercase;
                    letter-spacing: .08em; margin-bottom: 6px; }}
  .additional a {{ color: #c4b5fd; font-size: 0.9rem; text-decoration: none; display: block; }}
  .additional a:hover {{ text-decoration: underline; }}
  .nav {{ margin-top: 28px; padding-top: 20px; border-top: 1px solid #1e2330; }}
  .nav a {{ display: inline-block; background: #1e2330; color: #60a5fa; text-decoration: none;
            font-size: 0.85rem; font-weight: 600; padding: 10px 18px; border-radius: 8px;
            border: 1px solid #334155; transition: background 0.15s; }}
  .nav a:hover {{ background: #263347; }}
</style>
</head>
<body>
<header>
  <div><span class="badge">HBM Testing</span><span class="badge module-badge">M{topic_id} {module_name}</span></div>
  <h1>{topic}</h1>
  <div class="meta">{date_str} · Lesson {done_count + 1} of {total_count}</div>
</header>
{sections_html}
<div class="takeaways">
  <h2>⚡ Key Takeaways</h2>
  <ul>{takeaways_html}</ul>
</div>
{references_html}
{additional_html}
<div class="nav"><a href="../index.html">&#x2190; Back to Curriculum</a></div>
</body>
</html>"""

html_path = os.path.join(lesson_dir, f"{base_name}.html")
with open(html_path, "w", encoding="utf-8") as f:
    f.write(html)

print(f"Lesson saved: {html_path}")

# ── Rebuild index (curriculum main page) ─────────────────────────────────────
def parse_lesson_meta(fname):
    md_path = os.path.join(lesson_dir, fname.replace(".html", ".md"))
    if not os.path.exists(md_path):
        return fname.replace(".html", ""), None, fname[:10]
    with open(md_path, encoding="utf-8") as f:
        lines = [l.strip() for l in f.readlines()[:10]]
    title = next((l.lstrip("# ") for l in lines if l.startswith("# ")), fname)
    date_s = next((l.strip("*").strip() for l in lines
                   if any(m in l for m in ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"])), fname[:10])
    mod_id = None
    for l in lines:
        s = l.strip("*").strip()
        if s.startswith("Module "):
            mod_id = s.split(" -- ")[0].replace("Module ", "").strip()
            break
    return title, mod_id, date_s

topic_lesson_map = {}
pre_curriculum = []
all_html_files = sorted(os.listdir(lesson_dir))
for fname in all_html_files:
    if not fname.endswith(".html"):
        continue
    title, mod_id, date_s = parse_lesson_meta(fname)
    if mod_id:
        topic_lesson_map[mod_id] = (title, fname, date_s)
    else:
        pre_curriculum.append((date_s, title, fname))

total_topics = sum(len(m["topics"]) for m in curriculum["modules"])
done_topics = sum(1 for m in curriculum["modules"] for t in m["topics"] if t["done"])

modules_sections_html = ""
for m in curriculum["modules"]:
    done_m = sum(1 for t in m["topics"] if t["done"])
    total_m = len(m["topics"])
    pct = int(done_m / total_m * 100)
    topics_html = ""
    for t in m["topics"]:
        lesson_info = topic_lesson_map.get(t["id"])
        if lesson_info:
            l_title, l_fname, l_date = lesson_info
            topics_html += (
                f'<li class="done">'
                f'<span class="status">✅</span>'
                f'<span class="topic-info"><a href="daily-lessons/{l_fname}">{l_title}</a>'
                f'<span class="topic-date">{l_date}</span></span>'
                f'</li>\n'
            )
        elif t["done"]:
            short = t["title"].split(" -- ")[0]
            topics_html += (
                f'<li class="done">'
                f'<span class="status">✅</span>'
                f'<span class="topic-info"><span class="topic-title">{short}</span></span>'
                f'</li>\n'
            )
        else:
            short = t["title"].split(" -- ")[0]
            topics_html += (
                f'<li class="upcoming">'
                f'<span class="status">○</span>'
                f'<span class="topic-info"><span class="topic-title dim">{short}</span></span>'
                f'</li>\n'
            )
    modules_sections_html += f"""
<div class="module" id="module-{m['id']}">
  <div class="module-head">
    <div class="module-meta">
      <span class="module-num">M{m['id']}</span>
      <span class="module-name">{m['name']}</span>
    </div>
    <span class="module-prog">{done_m}/{total_m}</span>
  </div>
  <div class="progress-bar"><div class="progress-fill" style="width:{pct}%"></div></div>
  <ul class="topic-list">{topics_html}</ul>
</div>"""

pre_html = ""
if pre_curriculum:
    items = "".join(
        f'<li class="done"><span class="status">📄</span>'
        f'<span class="topic-info"><a href="daily-lessons/{fn}">{t}</a>'
        f'<span class="topic-date">{d}</span></span></li>\n'
        for d, t, fn in sorted(pre_curriculum)
    )
    pre_html = (
        f'<details class="module pre-curriculum" id="pre-curriculum">'
        f'<summary class="module-head"><div class="module-meta">'
        f'<span class="module-num dim">PRE</span>'
        f'<span class="module-name">Pre-Curriculum</span>'
        f'<span class="module-prog">{len(pre_curriculum)} lessons</span>'
        f'</div></summary><ul class="topic-list">{items}</ul></details>'
    )

with open("index.html", "w", encoding="utf-8") as f:
    f.write(f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>HBM Learning -- All Lessons</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         background: #0f1117; color: #e2e8f0; padding: 20px; max-width: 700px; margin: 0 auto; }}
  header {{ margin-bottom: 28px; }}
  h1 {{ font-size: 1.4rem; font-weight: 700; color: #f8fafc; margin-bottom: 4px; }}
  .sub {{ color: #64748b; font-size: 0.85rem; margin-bottom: 10px; }}
  .overall-prog {{ font-size: 0.9rem; color: #86efac; margin-bottom: 6px; }}
  .overall-bar {{ height: 4px; background: #1e2330; border-radius: 2px; margin-bottom: 24px; }}
  .overall-bar-fill {{ height: 4px; background: #22c55e; border-radius: 2px; }}
  .module {{ background: #1e2330; border-radius: 12px; padding: 18px 20px; margin-bottom: 14px; }}
  .module-head {{ display: flex; align-items: center; justify-content: space-between; margin-bottom: 10px; }}
  details.module summary {{ list-style: none; cursor: pointer; margin-bottom: 0; }}
  details.module summary::-webkit-details-marker {{ display: none; }}
  details.module[open] summary {{ margin-bottom: 10px; }}
  details.module summary .module-meta::before {{ content: "▶"; font-size: 0.65rem; color: #475569; margin-right: 4px; }}
  details.module[open] summary .module-meta::before {{ content: "▼"; }}
  .module-meta {{ display: flex; align-items: center; gap: 10px; }}
  .module-num {{ background: #1e3a5f; color: #60a5fa; font-size: 0.72rem; font-weight: 700;
                 padding: 2px 8px; border-radius: 4px; }}
  .module-num.dim {{ background: #1a1f2e; color: #475569; }}
  .module-name {{ font-weight: 700; color: #f1f5f9; font-size: 1rem; }}
  .module-prog {{ font-size: 0.8rem; color: #64748b; }}
  .progress-bar {{ height: 3px; background: #0f172a; border-radius: 2px; margin-bottom: 14px; }}
  .progress-fill {{ height: 3px; background: #3b82f6; border-radius: 2px; }}
  .topic-list {{ list-style: none; }}
  .topic-list li {{ display: flex; align-items: baseline; gap: 10px; padding: 8px 0;
                    border-bottom: 1px solid #0f172a; }}
  .topic-list li:last-child {{ border-bottom: none; }}
  .status {{ font-size: 0.85rem; flex-shrink: 0; width: 20px; }}
  .topic-info {{ display: flex; flex-direction: column; gap: 2px; flex: 1; }}
  .topic-info a {{ color: #60a5fa; text-decoration: none; font-size: 0.9rem; }}
  .topic-info a:hover {{ text-decoration: underline; }}
  .topic-title {{ font-size: 0.9rem; color: #cbd5e1; }}
  .topic-title.dim {{ color: #334155; }}
  .topic-date {{ font-size: 0.72rem; color: #475569; }}
</style>
</head>
<body>
<header>
  <h1>📚 HBM Learning Curriculum</h1>
  <div class="sub">Senior Test Engineer · 6 Modules · {total_topics} Topics</div>
  <div class="overall-prog">Overall progress: {done_topics}/{total_topics} topics completed</div>
  <div class="overall-bar"><div class="overall-bar-fill" style="width:{int(done_topics/total_topics*100)}%"></div></div>
</header>
{modules_sections_html}
{pre_html}
</body>
</html>""")

# ── Rebuild additional-learning index ─────────────────────────────────────────
_spec = importlib.util.spec_from_file_location("rebuild_index", "rebuild_index.py")
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)

print(f"Curriculum progress: {done_count + 1}/{total_count}")

# ── Mark curriculum done ──────────────────────────────────────────────────────
mark_done(topic_id)
_sp.run(["git", "add", "curriculum.json"], cwd=str(curriculum_path.parent.resolve()), check=False)

# ── Telegram ──────────────────────────────────────────────────────────────────
tg_token = os.environ.get("TELEGRAM_TOKEN")
tg_chat_id = os.environ.get("TELEGRAM_CHAT_ID")
if tg_token and tg_chat_id:
    progress_bar = f"{done_count + 1}/{total_count}"
    base_url = "https://allie0132.github.io/daily-semiconductor-learning"
    msg = (
        f"📚 *Daily Lesson -- {today}*\n"
        f"_Module {topic_id} · {module_name}_\n\n"
        f"*{topic}*\n\n"
        f"{summary}\n\n"
        f"📊 Progress: {progress_bar}\n\n"
        f"[Read Lesson]({base_url}/daily-lessons/{base_name}.html)  ·  "
        f"[Curriculum]({base_url}/index.html#module-{module['id']})"
    )
    payload = json.dumps({"chat_id": tg_chat_id, "text": msg, "parse_mode": "Markdown"}).encode()
    req = urllib.request.Request(
        f"https://api.telegram.org/bot{tg_token}/sendMessage",
        data=payload,
        headers={"Content-Type": "application/json"}
    )
    try:
        urllib.request.urlopen(req)
        print("Telegram sent.")
    except Exception as e:
        print(f"Telegram failed: {e}")
