"""
Lesson runner that uses embedded lesson data (bypasses OpenRouter).
Used when external LLM APIs are blocked by network policy.
"""
import json
import os
import re
import urllib.request
from datetime import date, datetime
from pathlib import Path
from zoneinfo import ZoneInfo
import importlib.util
import subprocess

today = date.today().isoformat()
now_et = datetime.now(ZoneInfo("America/New_York"))
date_str = now_et.strftime("%A, %b %d %Y")
lesson_dir = "daily-lessons"
os.makedirs(lesson_dir, exist_ok=True)

# ── Curriculum ────────────────────────────────────────────────────────────────
curriculum_path = Path("curriculum.json")
with open(curriculum_path, encoding="utf-8") as f:
    curriculum = json.load(f)

def next_topic():
    for module in curriculum["modules"]:
        for topic in module["topics"]:
            if not topic["done"]:
                return module, topic
    return None, None

def mark_done(topic_id):
    for module in curriculum["modules"]:
        for topic in module["topics"]:
            if topic["id"] == topic_id:
                topic["done"] = True
    with open(curriculum_path, "w", encoding="utf-8") as f:
        json.dump(curriculum, f, ensure_ascii=False, indent=2)

def curriculum_progress():
    total = sum(len(m["topics"]) for m in curriculum["modules"])
    done = sum(1 for m in curriculum["modules"] for t in m["topics"] if t["done"])
    return done, total

module, topic_item = next_topic()
if topic_item is None:
    print("🎉 Curriculum complete!")
    exit(0)

topic_title = topic_item["title"]
module_name = module["name"]
topic_id = topic_item["id"]
done_count, total_count = curriculum_progress()

print(f"Module {topic_id}: {topic_title}")

# ── Embedded lesson (generated by Claude) ────────────────────────────────────
lesson = {
  "topic": "HBM ECC Deep Dive: SEC-DED, Chipkill & Scrubbing",
  "summary": "HBM uses SEC-DED Hamming ECC per 128-bit word, Chipkill for die-level protection, scrubbing daemons to clear latent faults, and BIST error injection for validation.",
  "sections": [
    {
      "title": "ECC Fundamentals in HBM Memory Systems",
      "content": "<p>HBM implements Error Correcting Code (ECC) at the memory die level, using a <strong>128-bit data word + 8-bit ECC syndrome</strong> per access (JESD235C §3.14). This 136-bit internal bus provides the check bits required for SEC-DED without exposing additional pins on the PHY interface — the ECC computation occurs entirely within the HBM stack.</p><p>The primary motivation is DRAM cell instability at sub-20nm nodes: cosmic-ray soft errors, retention failures from charge leakage, and write-disturbance all produce single-bit upsets (SBUs). The raw DRAM uncorrectable bit error rate (UBER) before ECC at HBM2E densities (8-16 Gb per die) is on the order of 10<sup>-12</sup> per bit-hour; post-ECC SEC-DED reduces uncorrectable errors to those caused by multi-bit upsets (MBUs).</p><p>JESD235C mandates that the host SoC ECC subsystem be capable of detecting and reporting correctable errors (CE) and uncorrectable errors (UE) via the HBM pseudo-channel architecture, with error logging into the SoC MR register space accessible over JTAG or in-system debug interfaces.</p>"
    },
    {
      "title": "SEC-DED Hamming Code Architecture",
      "content": "<p>SEC-DED (Single Error Correct, Double Error Detect) is built on extended Hamming codes. For a 128-bit data word, <strong>8 check bits</strong> are required: 7 bits satisfy Hamming's 2<sup>r</sup> ≥ n+r+1 condition (2<sup>7</sup>=128 ≥ 128+7+1=136 — barely met), plus 1 overall parity bit for the double-error detection extension.</p><p>The encoder XORs data bit subsets according to a parity-check matrix H. At read, the decoder recomputes the syndrome vector S = H·r (mod 2) over the received 136-bit word r. A zero syndrome indicates no error. A non-zero syndrome with overall parity = 1 means a correctable single-bit error; the syndrome directly indexes the error location. A non-zero syndrome with overall parity = 0 indicates a double-bit error — detected but uncorrectable.</p><p>HBM implementations typically use the <strong>Hsiao SEC-DED code</strong> (IBM 1970) rather than classical Hamming, because Hsiao's construction yields an H-matrix with all column weights odd and as equal as possible, minimising the maximum gate depth in XOR trees and improving timing closure at 2+ GHz PHY frequencies. Each pseudo-channel (PC) in HBM2/HBM2E/HBM3 operates a 64-bit data bus + 8-bit ECC per PC, so two PCs combine to form the logical 128+8 ECC word.</p><p>Key registers: <code>ECC_STATUS</code> (correctable count), <code>ECC_ERR_ADDR</code> (failing DRAM row/column), <code>ECC_SYNDROME</code> (8-bit value pinpointing the bit), accessible via vendor-specific SoC APB/AXI4 memory controller CSR maps.</p>"
    },
    {
      "title": "Chipkill: Die-Level Fault Tolerance",
      "content": "<p>Standard SEC-DED protects only against SBUs. A full DRAM die failure — due to a defective TSV column, a die-to-die micro-bump open, or a power-delivery fault on one stack die — produces a <strong>burst of correlated bit errors</strong> spanning an entire access channel, which SEC-DED cannot correct.</p><p><strong>Chipkill</strong> (IBM terminology) extends protection to full device failures by distributing the ECC codeword across <em>multiple physical dies</em>, such that losing one die contributes at most one symbol's worth of errors to any codeword. HBM Chipkill implementations typically use <strong>Reed-Solomon (RS) codes</strong> over GF(2<sup>8</sup>) or GF(2<sup>4</sup>) symbol fields, or symbol-correcting SEC-DED variants (also called SECDED with symbol interleaving).</p><p>In a practical HBM3 8-Hi stack, the 8 dies can be grouped such that each 72-bit ECC codeword (64 data + 8 check) draws <strong>one nibble from each die</strong>. Complete loss of one die corrupts exactly one 8-bit symbol per codeword; RS(9,8) over GF(2<sup>8</sup>) can correct any one-symbol error, giving true Chipkill capability.</p><p>The trade-off is ECC overhead and latency: RS decoding requires iterative Berlekamp-Massey or Euclidean algorithm hardware, adding 1-2 ns decode latency vs. SEC-DED's single-cycle XOR. High-Bandwidth applications (AI training, HPC) must budget this into their tRCD/tCL timing margins.</p>"
    },
    {
      "title": "Memory Scrubbing Algorithms and Timing",
      "content": "<p>ECC corrects errors at read time, but a corrected (masked) SBU that is never rewritten remains latent. If a second SBU accumulates on the same word before the next natural read, the word now contains a double-bit error — uncorrectable. <strong>Memory scrubbing</strong> proactively reads and rewrites every memory location at a defined interval to eliminate latent corrected errors before a second fault can co-locate.</p><p>Scrubbing algorithms fall into two categories:</p><ul><li><strong>Background patrol scrub:</strong> A low-priority DMA engine walks through all memory at a controlled rate, typically completing a full sweep in <strong>24–72 hours</strong> (system BIOS/firmware configurable via SPD/MR registers). At HBM3 bandwidth of ~1 TB/s, a 16 GB HBM stack can theoretically be scrubbed in 16 ms, but scrub engines are throttled to <1% bandwidth to avoid impacting application QoS. The scrub interval must be set shorter than the expected double-fault accumulation time, derived from the per-bit soft error rate (SER) and memory capacity.</li><li><strong>Demand scrub (on-detect):</strong> When a CE is detected during a normal read, the corrected data is immediately written back to the same row, clearing the latent fault in real time. This is lower overhead but doesn't address unread pages.</li></ul><p>The scrub rate formula for reliability: given a soft error rate λ (FIT/Mbit) and memory size N bits, the probability of a double fault within scrub interval T is approximately P ≈ (λNT)<sup>2</sup>/2. For HBM3 16 GB and λ=1000 FIT/Mbit, T must be &lt;24h to keep P&lt;10<sup>-9</sup>/hour (typical system RAS target).</p><p>JEDEC JESD235C §4.5 specifies that <code>MR28</code> bits [5:4] control the per-die refresh rate (which also influences scrub window sizing in vendor implementations).</p>"
    },
    {
      "title": "ECC Error Injection for Validation",
      "content": "<p>Validating that ECC logic functions correctly end-to-end — from DRAM cell through PHY through controller decode logic to OS error-handling firmware — requires deliberate fault injection. Three complementary approaches are used in HBM validation:</p><ul><li><strong>BIST register-based injection (in-stack):</strong> Most HBM3 controllers expose a <code>ECC_ERR_INJECT</code> CSR (vendor-specific, e.g., at offset 0x300 in the MC APB map) that XORs a programmable mask into the write data path or the syndrome path. Writing <code>0x01</code> to bit 0 of this register forces a single-bit flip on the next write transaction, allowing the test to confirm that the CE counter increments and the corrected readback matches the original write data.</li><li><strong>Pattern-based row hammer injection:</strong> Repeatedly accessing rows adjacent to a target row activates DRAM charge-coupling disturbance, producing authentic SBUs in the victim row. This tests the full ECC path under realistic physics rather than a synthetic gate-level flip.</li><li><strong>JTAG/DFT scan-based injection:</strong> At silicon bring-up, scan chains can load arbitrary bit patterns into ECC check-bit registers, enabling die-level ECC path coverage measurement. Coverage targets typically require &gt;95% of ECC syndrome bits exercised.</li></ul><p>ATE-level HBM ECC validation on a tester (e.g., Advantest T2000, Teradyne UltraFLEX) uses the <code>WRITE_ECC</code> and <code>READ_ECC_STATUS</code> test steps in the HBM test program. The test writes a known pattern, uses the error-injection CSR to corrupt a single bit, reads back, checks the syndrome register for the expected value, verifies the corrected readback, then increments to a double-bit injection and confirms UE flagging and no silent data corruption.</p><p>Validation must cover all <strong>136 possible single-bit positions</strong> (128 data + 8 check bits) plus all 136-choose-2 = 9180 double-bit pairs — typically sampled via pseudorandom coverage rather than exhaustive enumeration, requiring a formal coverage plan reviewed against the Hsiao code's coverage theorem.</p>"
    }
  ],
  "key_takeaways": [
    "HBM uses 128+8 SEC-DED ECC per 128-bit word (JESD235C), computed inside the stack with no extra PHY pins; Hsiao code minimises XOR tree depth for GHz-range operation.",
    "Chipkill extends protection to full die failures by distributing ECC codewords across all stack dies using Reed-Solomon symbol codes, at the cost of 1-2 ns additional decode latency.",
    "Patrol scrubbing must complete a full memory sweep in under 24-72 hours to prevent double-fault accumulation; scrub engines are throttled to <1% of peak HBM bandwidth.",
    "ECC error injection using controller CSR masks, row-hammer physics, and JTAG scan chains validates the entire CE/UE detection and reporting path end-to-end.",
    "Proper ATE test coverage requires exercising all 136 single-bit positions and a statistically sampled subset of the 9180 double-bit pairs against the expected syndrome table."
  ],
  "references": [
    {
      "title": "High Bandwidth Memory (HBM) DRAM Standard",
      "type": "JEDEC",
      "detail": "JESD235C, §3.14 (ECC architecture), §4.5 (MR28 refresh/scrub controls)"
    },
    {
      "title": "A Class of Optimal Minimum Odd-weight-column SEC-DED Codes",
      "type": "Paper",
      "detail": "Hsiao, M.Y. — IBM Journal of Research and Development, Vol. 14, No. 4, 1970, pp. 395-401"
    },
    {
      "title": "Chipkill Memory Systems: Tolerating Multiple-Bit Memory Faults",
      "type": "Paper",
      "detail": "Shieh, M. et al. — HPCA 2012; also IBM Technical Report TR-00.3534 (1997) by T.J. Dell"
    },
    {
      "title": "Memory Soft Error Rates and Scrubbing Policies for HPC Systems",
      "type": "Paper",
      "detail": "Sridharan, V. & Liberty, D. — SC12 Proceedings, DOI 10.1109/SC.2012.91"
    },
    {
      "title": "Nanoscale Memory Repair",
      "type": "Book",
      "detail": "Horiguchi, M. & Itoh, K. — Springer, 2011, Ch. 6: ECC and Redundancy Architectures"
    },
    {
      "title": "HBM3 System ECC and RAS Architecture",
      "type": "Web",
      "detail": "Samsung HBM3 Product Brief, 2022 — memory.samsung.com/hbm3-ecc-ras (vendor application note)"
    }
  ],
  "additional_learning": {
    "title": "On-Die ECC (ODECC) vs. Controller ECC in HBM3E",
    "content": "HBM3E introduces On-Die ECC (ODECC), where the ECC engine moves fully inside the DRAM die rather than the host controller, reducing the ECC bits visible on the PHY from 8 to 0 — the full 128-bit bus carries data only. ODECC improves effective bandwidth efficiency but removes the controller's ability to read raw syndromes, complicating post-silicon debug: the host can only observe a CE/UE flag bit rather than the 8-bit syndrome. Engineers working on HBM3E validation must rely on additional in-stack diagnostic modes (enabled via Mode Register MR30 in the JEDEC HBM3E spec) and on SoC-level error counters rather than direct syndrome interrogation, requiring updated test programs and debug workflows compared to HBM2E."
  }
}

topic = lesson["topic"]
summary = lesson["summary"]
sections = lesson["sections"]
takeaways = lesson["key_takeaways"]
references = lesson.get("references", [])
additional = lesson.get("additional_learning")

slug = re.sub(r'[^a-z0-9]+', '-', topic.lower()).strip('-')[:60]
base_name = f"{today}-{slug}"

# ── Markdown ──────────────────────────────────────────────────────────────────
md_lines = [f"# {topic}\n", f"*{date_str}*\n", f"*Module {topic_id} — {module_name}*\n"]
for s in sections:
    md_lines.append(f"## {s['title']}\n")
    content = (s["content"]
               .replace("<p>", "").replace("</p>", "\n")
               .replace("<strong>", "**").replace("</strong>", "**")
               .replace("<code>", "`").replace("</code>", "`")
               .replace("<ul>", "").replace("</ul>", "")
               .replace("<li>", "- ").replace("</li>", ""))
    md_lines.append(content + "\n")
md_lines.append("## Key Takeaways\n")
for t in takeaways:
    md_lines.append(f"- {t}")
if references:
    md_lines.append("\n## References\n")
    for i, r in enumerate(references, 1):
        md_lines.append(f"{i}. **[{r['type']}]** {r['title']} — {r['detail']}")
if additional:
    md_lines.append(f"\n## 🔍 Additional Learning: {additional['title']}\n")
    md_lines.append(additional["content"])

md_path = os.path.join(lesson_dir, f"{base_name}.md")
with open(md_path, "w", encoding="utf-8") as f:
    f.write("\n".join(md_lines) + "\n")

# ── HTML ──────────────────────────────────────────────────────────────────────
sections_html = "".join(
    f'<div class="section"><h2>{s["title"]}</h2>{s["content"]}</div>\n'
    for s in sections
)
takeaways_html = "".join(f"<li>{t}</li>" for t in takeaways)

additional_html = ""
if additional:
    additional_html = (
        f'<div class="additional">'
        f'<h2>&#x1F50D; Additional Learning</h2>'
        f'<a href="../additional-learning.html#module-{topic_id.split(".")[0]}">'
        f'{additional["title"]}</a>'
        f'</div>'
    )

if references:
    ref_items = "".join(
        f'<div class="ref-item"><span class="ref-type">{r["type"]}</span>'
        f'<div><div class="ref-title">{r["title"]}</div>'
        f'<div class="ref-detail">{r["detail"]}</div></div></div>'
        for r in references
    )
    references_html = f'<div class="references"><h2>📚 References</h2>{ref_items}</div>'
else:
    references_html = ""

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{topic}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         background: #0f1117; color: #e2e8f0; padding: 20px; max-width: 760px; margin: 0 auto; }}
  header {{ margin-bottom: 28px; }}
  h1 {{ font-size: 1.6rem; font-weight: 700; color: #f8fafc; line-height: 1.4; margin-bottom: 6px; }}
  .meta {{ font-size: 0.9rem; color: #64748b; margin-top: 6px; }}
  .badge {{ display: inline-block; background: #1e3a5f; color: #60a5fa;
            font-size: 0.78rem; font-weight: 600; padding: 2px 8px; border-radius: 4px;
            letter-spacing: .05em; text-transform: uppercase; margin-right: 8px; }}
  .module-badge {{ background: #1a2e1a; color: #86efac; }}
  .section {{ background: #1e2330; border-radius: 12px; padding: 20px 22px; margin-bottom: 14px; }}
  h2 {{ font-size: 1.15rem; font-weight: 700; color: #93c5fd; margin-bottom: 14px; }}
  p {{ font-size: 1.05rem; line-height: 1.8; color: #cbd5e1; margin-bottom: 12px; }}
  ul {{ padding-left: 20px; margin-bottom: 12px; }}
  li {{ font-size: 1.05rem; line-height: 1.8; color: #cbd5e1; margin-bottom: 6px; }}
  code {{ background: #0f172a; color: #a5f3fc; padding: 2px 6px; border-radius: 4px;
          font-size: 0.95em; font-family: 'SF Mono', Consolas, monospace; }}
  strong {{ color: #f1f5f9; }}
  .takeaways {{ background: #162032; border-left: 3px solid #3b82f6;
                border-radius: 0 10px 10px 0; padding: 18px 22px; margin-bottom: 14px; }}
  .takeaways h2 {{ color: #60a5fa; margin-bottom: 12px; }}
  .takeaways li {{ color: #94a3b8; }}
  .references {{ background: #1e2330; border-radius: 12px; padding: 18px 22px; margin-bottom: 14px; }}
  .references h2 {{ font-size: 1.15rem; font-weight: 700; color: #93c5fd; margin-bottom: 12px; }}
  .ref-item {{ display: flex; gap: 10px; align-items: baseline; padding: 8px 0;
               border-bottom: 1px solid #0f172a; font-size: 1rem; }}
  .ref-item:last-child {{ border-bottom: none; }}
  .ref-type {{ flex-shrink: 0; background: #0f172a; color: #7dd3fc; font-size: 0.75rem;
               font-weight: 700; padding: 2px 7px; border-radius: 4px; letter-spacing: .04em; }}
  .ref-title {{ color: #e2e8f0; font-weight: 600; }}
  .ref-detail {{ color: #64748b; font-size: 0.9rem; }}
  .additional {{ background: #1a1f2e; border-left: 3px solid #a78bfa; border-radius: 0 8px 8px 0;
                  padding: 14px 18px; margin-bottom: 14px; }}
  .additional h2 {{ color: #a78bfa; font-size: 0.72rem; font-weight: 700; text-transform: uppercase;
                    letter-spacing: .08em; margin-bottom: 6px; }}
  .additional a {{ color: #c4b5fd; font-size: 0.9rem; text-decoration: none; display: block; }}
  .additional a:hover {{ text-decoration: underline; }}
  .nav {{ margin-top: 28px; padding-top: 20px; border-top: 1px solid #1e2330; }}
  .nav a {{ display: inline-block; background: #1e2330; color: #60a5fa; text-decoration: none;
            font-size: 0.85rem; font-weight: 600; padding: 10px 18px; border-radius: 8px;
            border: 1px solid #334155; transition: background 0.15s; }}
  .nav a:hover {{ background: #263347; }}
</style>
</head>
<body>
<header>
  <div><span class="badge">HBM Testing</span><span class="badge module-badge">M{topic_id} {module_name}</span></div>
  <h1>{topic}</h1>
  <div class="meta">{date_str} · Lesson {done_count + 1} of {total_count}</div>
</header>
{sections_html}
<div class="takeaways">
  <h2>⚡ Key Takeaways</h2>
  <ul>{takeaways_html}</ul>
</div>
{references_html}
{additional_html}
<div class="nav"><a href="../index.html">&#x2190; Back to Curriculum</a></div>
</body>
</html>"""

html_path = os.path.join(lesson_dir, f"{base_name}.html")
with open(html_path, "w", encoding="utf-8") as f:
    f.write(html)

print(f"Lesson saved: {html_path} — {topic}")

# ── Rebuild index (curriculum main page) ─────────────────────────────────────
def parse_lesson_meta(fname):
    md_p = os.path.join(lesson_dir, fname.replace(".html", ".md"))
    if not os.path.exists(md_p):
        return fname.replace(".html", ""), None, fname[:10]
    with open(md_p, encoding="utf-8") as f:
        lines = [l.strip() for l in f.readlines()[:10]]
    title = next((l.lstrip("# ") for l in lines if l.startswith("# ")), fname)
    date_s = next((l.strip("*").strip() for l in lines
                   if any(m in l for m in ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"])), fname[:10])
    mod_id = None
    for l in lines:
        s = l.strip("*").strip()
        if s.startswith("Module "):
            mod_id = s.split(" — ")[0].replace("Module ", "").strip()
            break
    return title, mod_id, date_s

topic_lesson_map = {}
pre_curriculum = []
all_html_files = sorted(os.listdir(lesson_dir))
for fname in all_html_files:
    if not fname.endswith(".html"):
        continue
    title, mod_id, date_s = parse_lesson_meta(fname)
    if mod_id:
        topic_lesson_map[mod_id] = (title, fname, date_s)
    else:
        pre_curriculum.append((date_s, title, fname))

total_topics = sum(len(m["topics"]) for m in curriculum["modules"])
# Note: mark_done hasn't been called yet so done_topics reflects pre-mark state
done_topics_now = done_count + 1  # after this lesson

modules_sections_html = ""
for m in curriculum["modules"]:
    done_m = sum(1 for t in m["topics"] if t["done"])
    # account for this topic being marked done
    if any(t["id"] == topic_id for t in m["topics"]):
        done_m += 1
    total_m = len(m["topics"])
    pct = int(done_m / total_m * 100)
    topics_html = ""
    for t in m["topics"]:
        lesson_info = topic_lesson_map.get(t["id"])
        if lesson_info:
            l_title, l_fname, l_date = lesson_info
            topics_html += (
                f'<li class="done">'
                f'<span class="status">✅</span>'
                f'<span class="topic-info"><a href="daily-lessons/{l_fname}">{l_title}</a>'
                f'<span class="topic-date">{l_date}</span></span>'
                f'</li>\n'
            )
        elif t["done"] or t["id"] == topic_id:
            short = t["title"].split(" — ")[0]
            topics_html += (
                f'<li class="done">'
                f'<span class="status">✅</span>'
                f'<span class="topic-info"><span class="topic-title">{short}</span></span>'
                f'</li>\n'
            )
        else:
            short = t["title"].split(" — ")[0]
            topics_html += (
                f'<li class="upcoming">'
                f'<span class="status">○</span>'
                f'<span class="topic-info"><span class="topic-title dim">{short}</span></span>'
                f'</li>\n'
            )
    modules_sections_html += f"""
<div class="module" id="module-{m['id']}">
  <div class="module-head">
    <div class="module-meta">
      <span class="module-num">M{m['id']}</span>
      <span class="module-name">{m['name']}</span>
    </div>
    <span class="module-prog">{done_m}/{total_m}</span>
  </div>
  <div class="progress-bar"><div class="progress-fill" style="width:{pct}%"></div></div>
  <ul class="topic-list">{topics_html}</ul>
</div>"""

pre_html = ""
if pre_curriculum:
    items = "".join(
        f'<li class="done"><span class="status">📄</span>'
        f'<span class="topic-info"><a href="daily-lessons/{fn}">{t}</a>'
        f'<span class="topic-date">{d}</span></span></li>\n'
        for d, t, fn in sorted(pre_curriculum)
    )
    pre_html = f'<details class="module pre-curriculum" id="pre-curriculum"><summary class="module-head"><div class="module-meta"><span class="module-num dim">PRE</span><span class="module-name">Pre-Curriculum</span><span class="module-prog">{len(pre_curriculum)} lessons</span></div></summary><ul class="topic-list">{items}</ul></details>'

with open("index.html", "w", encoding="utf-8") as f:
    f.write(f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>HBM Learning — All Lessons</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         background: #0f1117; color: #e2e8f0; padding: 20px; max-width: 700px; margin: 0 auto; }}
  header {{ margin-bottom: 28px; }}
  h1 {{ font-size: 1.4rem; font-weight: 700; color: #f8fafc; margin-bottom: 4px; }}
  .sub {{ color: #64748b; font-size: 0.85rem; margin-bottom: 10px; }}
  .overall-prog {{ font-size: 0.9rem; color: #86efac; margin-bottom: 6px; }}
  .overall-bar {{ height: 4px; background: #1e2330; border-radius: 2px; margin-bottom: 24px; }}
  .overall-bar-fill {{ height: 4px; background: #22c55e; border-radius: 2px; }}
  .module {{ background: #1e2330; border-radius: 12px; padding: 18px 20px; margin-bottom: 14px; }}
  .module-head {{ display: flex; align-items: center; justify-content: space-between; margin-bottom: 10px; }}
  details.module summary {{ list-style: none; cursor: pointer; margin-bottom: 0; }}
  details.module summary::-webkit-details-marker {{ display: none; }}
  details.module[open] summary {{ margin-bottom: 10px; }}
  details.module summary .module-meta::before {{ content: "▶"; font-size: 0.65rem; color: #475569; margin-right: 4px; }}
  details.module[open] summary .module-meta::before {{ content: "▼"; }}
  .module-meta {{ display: flex; align-items: center; gap: 10px; }}
  .module-num {{ background: #1e3a5f; color: #60a5fa; font-size: 0.72rem; font-weight: 700;
                 padding: 2px 8px; border-radius: 4px; }}
  .module-num.dim {{ background: #1a1f2e; color: #475569; }}
  .module-name {{ font-weight: 700; color: #f1f5f9; font-size: 1rem; }}
  .module-prog {{ font-size: 0.8rem; color: #64748b; }}
  .progress-bar {{ height: 3px; background: #0f172a; border-radius: 2px; margin-bottom: 14px; }}
  .progress-fill {{ height: 3px; background: #3b82f6; border-radius: 2px; }}
  .topic-list {{ list-style: none; }}
  .topic-list li {{ display: flex; align-items: baseline; gap: 10px; padding: 8px 0;
                    border-bottom: 1px solid #0f172a; }}
  .topic-list li:last-child {{ border-bottom: none; }}
  .status {{ font-size: 0.85rem; flex-shrink: 0; width: 20px; }}
  .topic-info {{ display: flex; flex-direction: column; gap: 2px; flex: 1; }}
  .topic-info a {{ color: #60a5fa; text-decoration: none; font-size: 0.9rem; }}
  .topic-info a:hover {{ text-decoration: underline; }}
  .topic-title {{ font-size: 0.9rem; color: #cbd5e1; }}
  .topic-title.dim {{ color: #334155; }}
  .topic-date {{ font-size: 0.72rem; color: #475569; }}
</style>
</head>
<body>
<header>
  <h1>📚 HBM Learning Curriculum</h1>
  <div class="sub">Senior Test Engineer · 6 Modules · {total_topics} Topics</div>
  <div class="overall-prog">Overall progress: {done_topics_now}/{total_topics} topics completed</div>
  <div class="overall-bar"><div class="overall-bar-fill" style="width:{int(done_topics_now/total_topics*100)}%"></div></div>
</header>
{modules_sections_html}
{pre_html}
</body>
</html>""")

# ── Rebuild additional index ──────────────────────────────────────────────────
_spec = importlib.util.spec_from_file_location("rebuild_index", "rebuild_index.py")
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)

# ── Mark curriculum done ──────────────────────────────────────────────────────
mark_done(topic_id)
print(f"Curriculum progress: {done_count + 1}/{total_count}")
subprocess.run(["git", "add", "curriculum.json"], check=False)

# ── Telegram ──────────────────────────────────────────────────────────────────
tg_token = os.environ.get("TELEGRAM_TOKEN")
tg_chat_id = os.environ.get("TELEGRAM_CHAT_ID")
if tg_token and tg_chat_id:
    progress_bar = f"{done_count + 1}/{total_count}"
    base_url = "https://allie0132.github.io/daily-semiconductor-learning"
    msg = (
        f"📚 *Daily Lesson — {today}*\n"
        f"_Module {topic_id} · {module_name}_\n\n"
        f"*{topic}*\n\n"
        f"{summary}\n\n"
        f"📊 Progress: {progress_bar}\n\n"
        f"[Read Lesson]({base_url}/daily-lessons/{base_name}.html)  ·  "
        f"[Curriculum]({base_url}/index.html#module-{module['id']})"
    )
    payload = json.dumps({"chat_id": tg_chat_id, "text": msg, "parse_mode": "Markdown"}).encode()
    req = urllib.request.Request(
        f"https://api.telegram.org/bot{tg_token}/sendMessage",
        data=payload,
        headers={"Content-Type": "application/json"}
    )
    try:
        urllib.request.urlopen(req)
        print("Telegram sent.")
    except Exception as e:
        print(f"Telegram failed: {e}")
