"""Run today's lesson with pre-generated content (bypasses OpenRouter API which is blocked)."""
import json
import os
import re
import subprocess
import time
import urllib.request
from datetime import date, datetime
from pathlib import Path
from zoneinfo import ZoneInfo

today = date.today().isoformat()
now_et = datetime.now(ZoneInfo("America/New_York"))
date_str = now_et.strftime("%A, %b %d %Y")
lesson_dir = "daily-lessons"
os.makedirs(lesson_dir, exist_ok=True)

# ── Curriculum ────────────────────────────────────────────────────────────────
curriculum_path = Path("curriculum.json")
with open(curriculum_path, encoding="utf-8") as f:
    curriculum = json.load(f)

def next_topic():
    for module in curriculum["modules"]:
        for topic in module["topics"]:
            if not topic["done"]:
                return module, topic
    return None, None

def mark_done(topic_id):
    for module in curriculum["modules"]:
        for topic in module["topics"]:
            if topic["id"] == topic_id:
                topic["done"] = True
    with open(curriculum_path, "w", encoding="utf-8") as f:
        json.dump(curriculum, f, ensure_ascii=False, indent=2)

def curriculum_progress():
    total = sum(len(m["topics"]) for m in curriculum["modules"])
    done = sum(1 for m in curriculum["modules"] for t in m["topics"] if t["done"])
    return done, total

module, topic_item = next_topic()
if topic_item is None:
    print("Curriculum complete!")
    exit(0)

topic_title = topic_item["title"]
module_name = module["name"]
topic_id = topic_item["id"]
done_count, total_count = curriculum_progress()

print(f"Module {topic_id}: {topic_title}")

# ── Pre-generated lesson content ──────────────────────────────────────────────
lesson = {
  "topic": "HBM PHY Eye Margin Characterization",
  "summary": "Bathtub curves, BER extrapolation to 1e-15, and margin budget allocation for HBM3 PHY validation at 6.4 Gbps.",
  "sections": [
    {
      "title": "Eye Diagram Fundamentals in HBM PHY Testing",
      "content": (
        "<p>An eye diagram is an overlay of all possible bit transitions accumulated over millions of UI (unit intervals), "
        "revealing the composite timing and voltage margin of a serial link. For HBM3 operating at 6.4 Gbps per pin "
        "(UI = 156.25 ps), the eye is generated by triggering an oscilloscope or ATE capture engine on the recovered "
        "clock and overlaying every received bit pattern.</p>"
        "<p>Two critical dimensions define eye quality:</p>"
        "<ul>"
        "<li><strong>Eye width (horizontal margin):</strong> Timing margin in ps or fraction of UI. JEDEC JESD235C "
        "requires a minimum open eye at the HBM die bump after package and interconnect de-embedding.</li>"
        "<li><strong>Eye height (vertical margin):</strong> Voltage margin in mV, bounded by noise floor, ISI, "
        "and supply-induced jitter.</li>"
        "</ul>"
        "<p>HBM2E (3.6 Gbps, UI = 277.8 ps) affords more timing margin than HBM3; validating to HBM3 specs "
        "therefore demands sub-picosecond ATE timing accuracy and calibrated interconnect de-embedding to the "
        "known-good reference plane.</p>"
      )
    },
    {
      "title": "Bathtub Curve Construction and Gaussian Extrapolation",
      "content": (
        "<p>A bathtub curve plots BER as a function of strobe offset from the ideal sampling point. The horizontal "
        "bathtub sweeps timing offset across the UI; the vertical bathtub sweeps the decision threshold in mV. "
        "The resulting curve resembles a bathtub in cross-section — steep walls at the eye edges where BER rises "
        "rapidly, and a flat floor at the minimum achievable BER near the eye center.</p>"
        "<p>Direct BER measurement at 10<sup>−15</sup> is impractical: at 6.4 Gbps, achieving one decade of "
        "statistical confidence requires ~3.3×10<sup>8</sup> seconds. Instead, engineers measure BER at the "
        "1×10<sup>−9</sup> to 1×10<sup>−10</sup> level (reachable in seconds per offset point) and extrapolate "
        "using Gaussian tail fitting:</p>"
        "<ul>"
        "<li><strong>Dual-Dirac model:</strong> Decomposes jitter into deterministic jitter (DJ, fixed amplitude, "
        "bounded) and random jitter (RJ, Gaussian, unbounded). BER is expressed as "
        "<code>BER = 0.5 × erfc((UI/2 − DJ/2 − t) / (RJ_rms × √2))</code>.</li>"
        "<li><strong>Q-factor:</strong> At a given BER, <code>Q = √2 × erfinv(1 − 2×BER)</code>. Plotting Q vs. "
        "offset on a linear scale reveals the Gaussian tails; extrapolating to Q ≈ 7.94 gives 10<sup>−15</sup>.</li>"
        "<li><strong>Minimum eye width at 10<sup>−15</sup>:</strong> Also called <em>BER eye width</em>, "
        "derived by subtracting both Gaussian tail extensions from the measured open eye.</li>"
        "</ul>"
        "<p>Commercial BERTScope instruments (Tektronix) and ATE BERT engines (Teradyne UltraFLEX HSD cards, "
        "Advantest T2000 DPPM option) perform this extrapolation natively, outputting the bathtub curve and "
        "fitted Gaussian parameters.</p>"
      )
    },
    {
      "title": "BER Targets and JEDEC Specifications",
      "content": (
        "<p>JEDEC JESD235C (HBM3) mandates an unformatted raw BER floor of <strong>1×10<sup>−15</sup></strong> "
        "per pin, measured at the receiver decision point inside the HBM die. This target drives system-level "
        "margin requirements because:</p>"
        "<ul>"
        "<li>HBM3 stacks use 1024-bit-wide interfaces (2 channels × 512 bits). At 1e-15 per pin, the aggregate "
        "channel BER is approximately 1.024×10<sup>−12</sup> — still below DRAM ECC correction capability.</li>"
        "<li>HBM ECC (SECDED on 128+8-bit sub-channels) provides single-bit correction; BER above the target "
        "risks ECC saturation during burst accesses.</li>"
        "</ul>"
        "<p>Key JEDEC margin parameters from JESD235C:</p>"
        "<ul>"
        "<li><code>tDQSQ</code> — DQS-to-DQ skew budget per channel, max ±5 ps (HBM3 Gen2)</li>"
        "<li><code>tQHS</code> — half swing timing, related to output driver linearity</li>"
        "<li><code>VREF</code> — reference voltage range 0.2×VDDQ to 0.8×VDDQ, centered at 0.5×VDDQ</li>"
        "<li>Receiver sensitivity: minimum differential swing ΔV ≥ 100 mV at 1e-15 BER</li>"
        "</ul>"
        "<p>JEDEC leaves receiver BER testing methodology to implementers, but JESD209-5B (LPDDR5) appendices "
        "provide normative guidance on bathtub extrapolation that HBM vendors commonly adopt.</p>"
      )
    },
    {
      "title": "Margin Budget Allocation Methodology",
      "content": (
        "<p>Total timing margin available at the receiver equals the raw eye width at the driver output minus "
        "all allocated losses across the signal path. The budget is expressed in UI fractions or ps, separated "
        "into deterministic and random components:</p>"
        "<ul>"
        "<li><strong>Package/substrate propagation:</strong> 2–5 ps RMS for flip-chip BGA interconnect; "
        "characterised per-package SKU using TDR and S-parameter extraction.</li>"
        "<li><strong>ISI (inter-symbol interference):</strong> Dominant at HBM3 speeds; quantified from "
        "channel insertion loss S21 — typically 1–4 dB at Nyquist causing 10–30 ps DJ.</li>"
        "<li><strong>Crosstalk:</strong> Adjacent-pin NEXT/FEXT, modeled in IBIS-AMI simulations; budgeted "
        "as bounded DJ contribution of 3–8 ps per aggressor.</li>"
        "<li><strong>PLL/DLL jitter:</strong> Clock source phase noise integrated across the loop bandwidth; "
        "contributes RJ of 0.5–1.5 ps RMS at the HBM PHY.</li>"
        "<li><strong>Supply-induced jitter (SIJ):</strong> VDDQ transient coupling into I/O drivers; mitigated "
        "by on-package decoupling but residual contribution is 2–5 ps.</li>"
        "<li><strong>Temperature/voltage (T/V) guard-band:</strong> 5–10 ps additional margin held in reserve "
        "for worst-case junction temperature and VDDQ tolerance (±3%).</li>"
        "</ul>"
        "<p>The margin allocation is documented in the SI (signal integrity) budget spreadsheet, cross-referenced "
        "against ATE measurement results. Any budget overage triggers a root-cause investigation before "
        "production release.</p>"
      )
    },
    {
      "title": "ATE Implementation: PHY Eye Margin Test Flow",
      "content": (
        "<p>On production ATE (Teradyne UltraFLEX with HSD-M cards, or Advantest T2000 with 64DSM modules), "
        "HBM PHY eye margin testing follows a structured flow:</p>"
        "<ul>"
        "<li><strong>Step 1 — Loopback configuration:</strong> The HBM controller (in the logic die) is "
        "programmed via MRS (Mode Register Set) to loop DQ data back through the PHY receive path. "
        "This isolates PHY margin from DRAM array timing.</li>"
        "<li><strong>Step 2 — PRBS pattern injection:</strong> ATE drives a PRBS-23 pattern at the DQ "
        "inputs; PRBS-23 maximises ISI stress while providing sufficient transitions for CDR lock.</li>"
        "<li><strong>Step 3 — Strobe sweep (timing bathtub):</strong> The ATE timing edge is offset in "
        "1–2 ps increments across ±40% UI from nominal center. BER is accumulated for ~100 ms per point "
        "(10<sup>−9</sup> floor at 6.4 Gbps = ~1.56×10<sup>9</sup> bits).</li>"
        "<li><strong>Step 4 — Threshold sweep (voltage bathtub):</strong> VREF DAC is swept ±80 mV from "
        "mid-rail in 2 mV steps; BER accumulated per point.</li>"
        "<li><strong>Step 5 — Dual-Dirac fit and extrapolation:</strong> ATE software fits Gaussian tails "
        "to each wall of the bathtub and reports RJ, DJ, and BER eye width at 10<sup>−15</sup>.</li>"
        "<li><strong>Step 6 — Bin/pass criteria:</strong> BER eye width ≥ spec limit (typically 0.3 UI "
        "after all budget allocations); voltage margin ≥ 150 mV. Parts failing either criterion are "
        "downbinned or retested at relaxed conditions to characterize the failure mode.</li>"
        "</ul>"
        "<p>Test time optimisation: production sites typically run a fast <em>go/no-go</em> BER check at "
        "±25% UI (2–5 s per device) with full bathtub sweeps reserved for characterisation lots and "
        "correlation vehicles.</p>"
      )
    }
  ],
  "key_takeaways": [
    "Bathtub curves enable 10^-15 BER validation through Gaussian extrapolation from short 10^-9 measurements, since direct 10^-15 testing is physically impractical at HBM3 speeds.",
    "Margin budget allocation must account for ISI, crosstalk, PLL jitter, supply-induced jitter, and T/V guard-band — any overage against the JEDEC JESD235C eye spec requires root-cause investigation before release.",
    "Production ATE PHY margin testing uses PHY loopback with PRBS-23, sweeps timing and voltage in fine steps, then applies Dual-Dirac fitting; pass/fail thresholds are typically 0.3 UI horizontal and 150 mV vertical at the 10^-15 BER contour."
  ],
  "references": [
    {
      "title": "JEDEC JESD235C: High Bandwidth Memory (HBM3) DRAM Standard",
      "type": "JEDEC",
      "detail": "Sections 4 (electrical specs), 8 (timing parameters), Annex B (eye diagram requirements)"
    },
    {
      "title": "JEDEC JESD209-5B: LPDDR5/5X Standard — BER Measurement Annex",
      "type": "JEDEC",
      "detail": "Annex F: BER extrapolation methodology and bathtub curve test procedures"
    },
    {
      "title": "Tektronix BERTScope BSA286CL: Bathtub Curve and Jitter Analysis Application Note",
      "type": "Datasheet",
      "detail": "80W-20750-0, Rev. C — Dual-Dirac jitter model, Q-factor extrapolation, BERT eye width calculation"
    },
    {
      "title": "Buchwald, A. & Healey, A.: 'Jitter in high-speed serial interfaces'",
      "type": "Paper",
      "detail": "IEEE Communications Magazine, Vol. 42, No. 12, 2004 — RJ/DJ decomposition and BER prediction"
    },
    {
      "title": "SK Hynix HBM3 Product Brief: GDDR6/HBM3 PHY Signal Integrity",
      "type": "Datasheet",
      "detail": "HBM3 Gen2 (MKH28B510BA-0M0) — receiver sensitivity, eye mask, and loopback test mode description"
    },
    {
      "title": "Teradyne UltraFLEX HSD-M Hardware Reference Manual",
      "type": "Datasheet",
      "detail": "Chapter 9: BERT mode, timing calibration, and bathtub curve generation — timing resolution ≤1 ps"
    }
  ],
  "additional_learning": {
    "title": "2D BER Contour Mapping for PHY Margin Corners",
    "content": (
      "Beyond 1D bathtub curves, advanced HBM PHY characterisation employs 2D BER contour maps that sweep "
      "both timing offset and voltage threshold simultaneously, plotting iso-BER contours (e.g. 10^-9, 10^-12, "
      "extrapolated 10^-15) as closed ovals in the timing-voltage plane. The area enclosed by the 10^-15 "
      "contour is directly comparable to JEDEC's 2D eye mask, revealing asymmetric margin that 1D bathtubs "
      "miss — for example, a device with adequate horizontal margin but a voltage-timing interaction that "
      "degrades both simultaneously under supply droop. Instruments such as the Keysight J-BERT N4903B and "
      "Tektronix BERTScope BSA286C support 2D eye scan modes; on ATE, equivalent functionality is achieved "
      "by scripting nested timing/voltage sweeps with the BERT engine."
    )
  }
}

topic = lesson["topic"]
summary = lesson["summary"]
sections = lesson["sections"]
takeaways = lesson["key_takeaways"]
references = lesson.get("references", [])
additional = lesson.get("additional_learning")

slug = re.sub(r'[^a-z0-9]+', '-', topic.lower()).strip('-')[:60]
base_name = f"{today}-{slug}"

# ── Markdown ──────────────────────────────────────────────────────────────────
md_lines = [f"# {topic}\n", f"*{date_str}*\n", f"*Module {topic_id} — {module_name}*\n"]
for s in sections:
    md_lines.append(f"## {s['title']}\n")
    content = (s["content"]
               .replace("<p>", "").replace("</p>", "\n")
               .replace("<strong>", "**").replace("</strong>", "**")
               .replace("<code>", "`").replace("</code>", "`")
               .replace("<ul>", "").replace("</ul>", "")
               .replace("<li>", "- ").replace("</li>", ""))
    md_lines.append(content + "\n")
md_lines.append("## Key Takeaways\n")
for t in takeaways:
    md_lines.append(f"- {t}")
if references:
    md_lines.append("\n## References\n")
    for i, r in enumerate(references, 1):
        md_lines.append(f"{i}. **[{r['type']}]** {r['title']} — {r['detail']}")
if additional:
    md_lines.append(f"\n## Additional Learning: {additional['title']}\n")
    md_lines.append(additional["content"])

md_path = os.path.join(lesson_dir, f"{base_name}.md")
with open(md_path, "w", encoding="utf-8") as f:
    f.write("\n".join(md_lines) + "\n")

# ── HTML ──────────────────────────────────────────────────────────────────────
sections_html = "".join(
    f'<div class="section"><h2>{s["title"]}</h2>{s["content"]}</div>\n'
    for s in sections
)
takeaways_html = "".join(f"<li>{t}</li>" for t in takeaways)

additional_html = ""
if additional:
    additional_html = (
        f'<div class="additional">'
        f'<h2>&#x1F50D; Additional Learning</h2>'
        f'<a href="../additional-learning.html#module-{topic_id.split(".")[0]}">'
        f'{additional["title"]}</a>'
        f'</div>'
    )

if references:
    ref_items = "".join(
        f'<div class="ref-item"><span class="ref-type">{r["type"]}</span>'
        f'<div><div class="ref-title">{r["title"]}</div>'
        f'<div class="ref-detail">{r["detail"]}</div></div></div>'
        for r in references
    )
    references_html = f'<div class="references"><h2>📚 References</h2>{ref_items}</div>'
else:
    references_html = ""

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{topic}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         background: #0f1117; color: #e2e8f0; padding: 20px; max-width: 760px; margin: 0 auto; }}
  header {{ margin-bottom: 28px; }}
  h1 {{ font-size: 1.6rem; font-weight: 700; color: #f8fafc; line-height: 1.4; margin-bottom: 6px; }}
  .meta {{ font-size: 0.9rem; color: #64748b; margin-top: 6px; }}
  .badge {{ display: inline-block; background: #1e3a5f; color: #60a5fa;
            font-size: 0.78rem; font-weight: 600; padding: 2px 8px; border-radius: 4px;
            letter-spacing: .05em; text-transform: uppercase; margin-right: 8px; }}
  .module-badge {{ background: #1a2e1a; color: #86efac; }}
  .section {{ background: #1e2330; border-radius: 12px; padding: 20px 22px; margin-bottom: 14px; }}
  h2 {{ font-size: 1.15rem; font-weight: 700; color: #93c5fd; margin-bottom: 14px; }}
  p {{ font-size: 1.05rem; line-height: 1.8; color: #cbd5e1; margin-bottom: 12px; }}
  ul {{ padding-left: 20px; margin-bottom: 12px; }}
  li {{ font-size: 1.05rem; line-height: 1.8; color: #cbd5e1; margin-bottom: 6px; }}
  code {{ background: #0f172a; color: #a5f3fc; padding: 2px 6px; border-radius: 4px;
          font-size: 0.95em; font-family: 'SF Mono', Consolas, monospace; }}
  strong {{ color: #f1f5f9; }}
  .takeaways {{ background: #162032; border-left: 3px solid #3b82f6;
                border-radius: 0 10px 10px 0; padding: 18px 22px; margin-bottom: 14px; }}
  .takeaways h2 {{ color: #60a5fa; margin-bottom: 12px; }}
  .takeaways li {{ color: #94a3b8; }}
  .references {{ background: #1e2330; border-radius: 12px; padding: 18px 22px; margin-bottom: 14px; }}
  .references h2 {{ font-size: 1.15rem; font-weight: 700; color: #93c5fd; margin-bottom: 12px; }}
  .ref-item {{ display: flex; gap: 10px; align-items: baseline; padding: 8px 0;
               border-bottom: 1px solid #0f172a; font-size: 1rem; }}
  .ref-item:last-child {{ border-bottom: none; }}
  .ref-type {{ flex-shrink: 0; background: #0f172a; color: #7dd3fc; font-size: 0.75rem;
               font-weight: 700; padding: 2px 7px; border-radius: 4px; letter-spacing: .04em; }}
  .ref-title {{ color: #e2e8f0; font-weight: 600; }}
  .ref-detail {{ color: #64748b; font-size: 0.9rem; }}
  .additional {{ background: #1a1f2e; border-left: 3px solid #a78bfa; border-radius: 0 8px 8px 0;
                  padding: 14px 18px; margin-bottom: 14px; }}
  .additional h2 {{ color: #a78bfa; font-size: 0.72rem; font-weight: 700; text-transform: uppercase;
                    letter-spacing: .08em; margin-bottom: 6px; }}
  .additional a {{ color: #c4b5fd; font-size: 0.9rem; text-decoration: none; display: block; }}
  .additional a:hover {{ text-decoration: underline; }}
  .nav {{ margin-top: 28px; padding-top: 20px; border-top: 1px solid #1e2330; }}
  .nav a {{ display: inline-block; background: #1e2330; color: #60a5fa; text-decoration: none;
            font-size: 0.85rem; font-weight: 600; padding: 10px 18px; border-radius: 8px;
            border: 1px solid #334155; transition: background 0.15s; }}
  .nav a:hover {{ background: #263347; }}
</style>
</head>
<body>
<header>
  <div><span class="badge">HBM Testing</span><span class="badge module-badge">M{topic_id} {module_name}</span></div>
  <h1>{topic}</h1>
  <div class="meta">{date_str} · Lesson {done_count + 1} of {total_count}</div>
</header>
{sections_html}
<div class="takeaways">
  <h2>⚡ Key Takeaways</h2>
  <ul>{takeaways_html}</ul>
</div>
{references_html}
{additional_html}
<div class="nav"><a href="../index.html">&#x2190; Back to Curriculum</a></div>
</body>
</html>"""

html_path = os.path.join(lesson_dir, f"{base_name}.html")
with open(html_path, "w", encoding="utf-8") as f:
    f.write(html)

print(f"Lesson saved: {html_path}")
print(f"  Topic: {topic}")

# ── Rebuild index (curriculum main page) ─────────────────────────────────────
def parse_lesson_meta(fname):
    md_path_l = os.path.join(lesson_dir, fname.replace(".html", ".md"))
    if not os.path.exists(md_path_l):
        return fname.replace(".html", ""), None, fname[:10]
    with open(md_path_l, encoding="utf-8") as f:
        lines = [l.strip() for l in f.readlines()[:10]]
    title = next((l.lstrip("# ") for l in lines if l.startswith("# ")), fname)
    date_s = next((l.strip("*").strip() for l in lines
                   if any(m in l for m in ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"])), fname[:10])
    mod_id = None
    for l in lines:
        s = l.strip("*").strip()
        if s.startswith("Module "):
            mod_id = s.split(" — ")[0].replace("Module ", "").strip()
            break
    return title, mod_id, date_s

topic_lesson_map = {}
pre_curriculum = []
all_html_files = sorted(os.listdir(lesson_dir))
for fname in all_html_files:
    if not fname.endswith(".html"):
        continue
    title, mod_id, date_s = parse_lesson_meta(fname)
    if mod_id:
        topic_lesson_map[mod_id] = (title, fname, date_s)
    else:
        pre_curriculum.append((date_s, title, fname))

# Mark done first so progress count is accurate
mark_done(topic_id)
print(f"Curriculum progress: {done_count + 1}/{total_count}")

# Re-read curriculum for accurate counts
with open(curriculum_path, encoding="utf-8") as f:
    curriculum = json.load(f)

total_topics = sum(len(m["topics"]) for m in curriculum["modules"])
done_topics = sum(1 for m in curriculum["modules"] for t in m["topics"] if t["done"])

modules_sections_html = ""
for m in curriculum["modules"]:
    done_m = sum(1 for t in m["topics"] if t["done"])
    total_m = len(m["topics"])
    pct = int(done_m / total_m * 100)
    topics_html = ""
    for t in m["topics"]:
        lesson_info = topic_lesson_map.get(t["id"])
        if lesson_info:
            l_title, l_fname, l_date = lesson_info
            topics_html += (
                f'<li class="done">'
                f'<span class="status">✅</span>'
                f'<span class="topic-info"><a href="daily-lessons/{l_fname}">{l_title}</a>'
                f'<span class="topic-date">{l_date}</span></span>'
                f'</li>\n'
            )
        elif t["done"]:
            short = t["title"].split(" — ")[0]
            topics_html += (
                f'<li class="done">'
                f'<span class="status">✅</span>'
                f'<span class="topic-info"><span class="topic-title">{short}</span></span>'
                f'</li>\n'
            )
        else:
            short = t["title"].split(" — ")[0]
            topics_html += (
                f'<li class="upcoming">'
                f'<span class="status">○</span>'
                f'<span class="topic-info"><span class="topic-title dim">{short}</span></span>'
                f'</li>\n'
            )
    modules_sections_html += f"""
<div class="module" id="module-{m['id']}">
  <div class="module-head">
    <div class="module-meta">
      <span class="module-num">M{m['id']}</span>
      <span class="module-name">{m['name']}</span>
    </div>
    <span class="module-prog">{done_m}/{total_m}</span>
  </div>
  <div class="progress-bar"><div class="progress-fill" style="width:{pct}%"></div></div>
  <ul class="topic-list">{topics_html}</ul>
</div>"""

pre_html = ""
if pre_curriculum:
    items = "".join(
        f'<li class="done"><span class="status">📄</span>'
        f'<span class="topic-info"><a href="daily-lessons/{fn}">{t}</a>'
        f'<span class="topic-date">{d}</span></span></li>\n'
        for d, t, fn in sorted(pre_curriculum)
    )
    pre_html = (
        f'<details class="module pre-curriculum" id="pre-curriculum">'
        f'<summary class="module-head"><div class="module-meta">'
        f'<span class="module-num dim">PRE</span>'
        f'<span class="module-name">Pre-Curriculum</span>'
        f'<span class="module-prog">{len(pre_curriculum)} lessons</span>'
        f'</div></summary><ul class="topic-list">{items}</ul></details>'
    )

with open("index.html", "w", encoding="utf-8") as f:
    f.write(f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>HBM Learning — All Lessons</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         background: #0f1117; color: #e2e8f0; padding: 20px; max-width: 700px; margin: 0 auto; }}
  header {{ margin-bottom: 28px; }}
  h1 {{ font-size: 1.4rem; font-weight: 700; color: #f8fafc; margin-bottom: 4px; }}
  .sub {{ color: #64748b; font-size: 0.85rem; margin-bottom: 10px; }}
  .overall-prog {{ font-size: 0.9rem; color: #86efac; margin-bottom: 6px; }}
  .overall-bar {{ height: 4px; background: #1e2330; border-radius: 2px; margin-bottom: 24px; }}
  .overall-bar-fill {{ height: 4px; background: #22c55e; border-radius: 2px; }}
  .module {{ background: #1e2330; border-radius: 12px; padding: 18px 20px; margin-bottom: 14px; }}
  .module-head {{ display: flex; align-items: center; justify-content: space-between; margin-bottom: 10px; }}
  details.module summary {{ list-style: none; cursor: pointer; margin-bottom: 0; }}
  details.module summary::-webkit-details-marker {{ display: none; }}
  details.module[open] summary {{ margin-bottom: 10px; }}
  details.module summary .module-meta::before {{ content: "▶"; font-size: 0.65rem; color: #475569; margin-right: 4px; }}
  details.module[open] summary .module-meta::before {{ content: "▼"; }}
  .module-meta {{ display: flex; align-items: center; gap: 10px; }}
  .module-num {{ background: #1e3a5f; color: #60a5fa; font-size: 0.72rem; font-weight: 700;
                 padding: 2px 8px; border-radius: 4px; }}
  .module-num.dim {{ background: #1a1f2e; color: #475569; }}
  .module-name {{ font-weight: 700; color: #f1f5f9; font-size: 1rem; }}
  .module-prog {{ font-size: 0.8rem; color: #64748b; }}
  .progress-bar {{ height: 3px; background: #0f172a; border-radius: 2px; margin-bottom: 14px; }}
  .progress-fill {{ height: 3px; background: #3b82f6; border-radius: 2px; }}
  .topic-list {{ list-style: none; }}
  .topic-list li {{ display: flex; align-items: baseline; gap: 10px; padding: 8px 0;
                    border-bottom: 1px solid #0f172a; }}
  .topic-list li:last-child {{ border-bottom: none; }}
  .status {{ font-size: 0.85rem; flex-shrink: 0; width: 20px; }}
  .topic-info {{ display: flex; flex-direction: column; gap: 2px; flex: 1; }}
  .topic-info a {{ color: #60a5fa; text-decoration: none; font-size: 0.9rem; }}
  .topic-info a:hover {{ text-decoration: underline; }}
  .topic-title {{ font-size: 0.9rem; color: #cbd5e1; }}
  .topic-title.dim {{ color: #334155; }}
  .topic-date {{ font-size: 0.72rem; color: #475569; }}
</style>
</head>
<body>
<header>
  <h1>📚 HBM Learning Curriculum</h1>
  <div class="sub">Senior Test Engineer · 6 Modules · {total_topics} Topics</div>
  <div class="overall-prog">Overall progress: {done_topics}/{total_topics} topics completed</div>
  <div class="overall-bar"><div class="overall-bar-fill" style="width:{int(done_topics/total_topics*100)}%"></div></div>
</header>
{modules_sections_html}
{pre_html}
</body>
</html>""")

print("index.html rebuilt")

# ── Rebuild additional learning page ─────────────────────────────────────────
import importlib.util, sys as _sys
try:
    _spec = importlib.util.spec_from_file_location("rebuild_index", "rebuild_index.py")
    _mod = importlib.util.module_from_spec(_spec)
    _spec.loader.exec_module(_mod)
    print("rebuild_index.py executed")
except Exception as e:
    print(f"rebuild_index.py skipped: {e}")

# Stage curriculum.json
subprocess.run(["git", "add", "curriculum.json"], check=False)
print("curriculum.json staged")

# ── Telegram ──────────────────────────────────────────────────────────────────
tg_token = os.environ.get("TELEGRAM_TOKEN")
tg_chat_id = os.environ.get("TELEGRAM_CHAT_ID")
if tg_token and tg_chat_id:
    progress_bar = f"{done_count + 1}/{total_count}"
    base_url = "https://allie0132.github.io/daily-semiconductor-learning"
    msg = (
        f"📚 *Daily Lesson — {today}*\n"
        f"_Module {topic_id} · {module_name}_\n\n"
        f"*{topic}*\n\n"
        f"{summary}\n\n"
        f"📊 Progress: {progress_bar}\n\n"
        f"[Read Lesson]({base_url}/daily-lessons/{base_name}.html)  ·  "
        f"[Curriculum]({base_url}/index.html#module-{module['id']})"
    )
    payload = json.dumps({"chat_id": tg_chat_id, "text": msg, "parse_mode": "Markdown"}).encode()
    req = urllib.request.Request(
        f"https://api.telegram.org/bot{tg_token}/sendMessage",
        data=payload,
        headers={"Content-Type": "application/json"}
    )
    try:
        with urllib.request.urlopen(req) as resp:
            result = json.loads(resp.read())
            if result.get("ok"):
                print("Telegram sent.")
            else:
                print(f"Telegram API error: {result}")
    except Exception as e:
        print(f"Telegram failed: {e}")
